import { runEvent, type EventMember } from './event';

/**
 * The official record of one recorded event.
 *
 * This is the whole recording: a master seed, the roster it was drawn for, and the
 * checksum it produced. A few hundred bytes. The website ships no simulation data at
 * all — it re-runs `runEvent` from `masterSeed` and `members`, and `verifyRecord` is the
 * same check the site performs to confirm the replay still matches.
 */
export interface EventRecord {
  version: 1;
  leagueId: string;
  label: string;
  masterSeed: number;
  members: EventMember[];
  /** Checksum of the result this seed produced when it was recorded. */
  checksum: string;
  /**
   * Human-readable timestamp for the admin's benefit only. Never read by the simulation —
   * `Date` is banned in `src/sim/`, so this is generated by the recording tool and passed
   * in as a plain string.
   */
  recordedAt: string;
}

export interface CreateRecordInput {
  leagueId: string;
  label: string;
  masterSeed: number;
  members: EventMember[];
  recordedAt: string;
}

/** Runs the event once and packages the result as an official record. */
export function createRecord(input: CreateRecordInput): EventRecord {
  const result = runEvent({ masterSeed: input.masterSeed, members: input.members });
  return {
    version: 1,
    leagueId: input.leagueId,
    label: input.label,
    masterSeed: input.masterSeed,
    members: input.members,
    checksum: result.checksum,
    recordedAt: input.recordedAt,
  };
}

export interface VerifyResult {
  valid: boolean;
  expectedChecksum: string;
  actualChecksum: string;
}

/**
 * Re-runs the event from the record's seed and roster, and reports whether the checksum
 * still matches. This is the entire trust model: if it verifies, the record is genuine.
 */
export function verifyRecord(record: EventRecord): VerifyResult {
  const result = runEvent({ masterSeed: record.masterSeed, members: record.members });
  return {
    valid: result.checksum === record.checksum,
    expectedChecksum: record.checksum,
    actualChecksum: result.checksum,
  };
}
