/**
 * The checksum gate: re-runs the whole event from a recorded seed and roster, and
 * reports whether the result still matches what was recorded. See
 * `docs/superpowers/specs/2026-08-11-website-design.md` §4 ("The check on load").
 *
 * This is the entire trust model. `data/official-event.json` is a few hundred bytes —
 * a master seed, the roster it was drawn for, and a checksum — not the event itself.
 * The site re-derives the whole thing from that seed on every load and refuses to show
 * anything if the derivation disagrees, because a mismatch means `src/sim/` changed
 * after the event was recorded, and a *different* draft order than the one the admin
 * approved is worse than an error screen.
 *
 * Deliberately pure — no DOM, no timers. `./boot.ts` is what shows a loading state,
 * calls this, and either mounts the router or blocks with an error.
 */
import { runEvent } from '../sim/event/event';
import type { EventRecord } from '../sim/event/record';
import officialRecordData from '../../data/official-event.json';

/** The record shipped with the site. Typed via a cast, not structural validation — this
 *  file is generated by `npm run record -- --save`, which already writes the exact
 *  `EventRecord` shape, so re-validating its structure here would only be checking the
 *  admin tool against itself. */
const OFFICIAL_RECORD = officialRecordData as EventRecord;

export interface ChecksumCheck {
  ok: boolean;
  expectedChecksum: string;
  actualChecksum: string;
  record: EventRecord;
}

/**
 * Re-runs `runEvent` from `record`'s own seed and roster and compares checksums.
 * Exported separately from `checkOfficialRecord` so a test can hand this a record
 * crafted to disagree, without touching the real data file to prove the gate blocks.
 */
export function checkRecord(record: EventRecord): ChecksumCheck {
  const result = runEvent({ masterSeed: record.masterSeed, members: record.members });
  return {
    ok: result.checksum === record.checksum,
    expectedChecksum: record.checksum,
    actualChecksum: result.checksum,
    record,
  };
}

/** The real official record shipped with the site. */
export function officialRecord(): EventRecord {
  return OFFICIAL_RECORD;
}

/** Checks the real shipped record — what the site calls on boot. */
export function checkOfficialRecord(): ChecksumCheck {
  return checkRecord(OFFICIAL_RECORD);
}
